export const strings = {
  paymentRequiredTitle: 'Payment Required',
  paymentRequiredMessage: 'You need to pay the full amount for the booking and confirmation of trip.',
  confirmTrip: 'Confirm Trip',
  addBooking: 'Add Booking',
  searchClients: 'Search clients...',
  filterByStatus: 'Filter by Status',
  filterByAgent: 'Filter by Agent Name',
  noClientsFound: 'No clients found',
  clientDetails: 'Client Details',
  payments: 'Payments',
  home: 'Home',
  clients: 'Clients',
  alerts: 'Alerts',
  profile: 'Profile',
  bookings: 'Bookings',
  newBookingFor: 'New Booking for',
  busName: 'Bus name',
  bookingRoutes: 'Route Details',
  noBookingsFound: 'No Bookings found.',
  bookingSummary: 'Booking Summary',
  bookingSummaryDescription: 'See booking progress across bus reservations.',
  total: 'Total',
  confirmed: 'Confirmed',
  buses: 'Buses',
  reminders: 'Reminders & Alerts',
  dashboard: 'Dashboard',
  clientList: 'Client List',
  addClient: 'Add Client',
  editClient: 'Edit Client',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  confirm: 'Confirm',
  ok: 'OK',
  error: 'Error',
  success: 'Success',
  loading: 'Loading...',
  name: 'Name',
  contact: 'Contact',
  destination: 'Destination',
  travelDates: 'Travel Dates',
  travelers: 'Travelers',
  leadSource: 'Lead Source',
  assignedAgent: 'Assigned Agent',
  status: 'Status',
  amount: 'Amount',
  amountToPay: 'Amount To Pay',
  addPaymentFor: 'Add Payment for',
  totalCost: 'Total Cost',
  totalPaid: 'Total Paid',
  savePayment: 'Save Payment',
  noPaymentsFoundFor: 'No payments found for',
  noPaymentsYet: 'No payments yet',
  selectClientError: 'Select a client to add payment.',
  validPaymentAmountError: 'Enter a valid payment amount',
  addDescriptionError: 'Add a description',
  paymentConfirmationRequired: 'Payments can be added after the client is confirmed.',
  type: 'Type',
  date: 'Date',
  description: 'Description',
  pending: 'Pending',
  fullPaymentRequired: 'Full payment required',
  logout: 'Logout',
  logoutConfirmTitle: 'Logout',
  logoutConfirmMessage: 'Are you sure you want to logout?',
  defaultUserName: 'Travel Agent',
  defaultEmail: 'agent@travelcompany.com',
  role: 'Travel Agent Manager',
  agentDetails: 'Agent Details',
  manager: 'Manager',
  active: 'Active',
  experience: '3+ Years',
  leads: 'Leads',
  totalBookings: 'Total Bookings',
  totalPaymentReceived: 'Total Payment Received',
  ReasonCancellation: 'Reason for cancellation',
  RefundAmount: 'Refund amount',
};